### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mvroosmalen1970** [r0bb10/ESPHome-DFRobot-pH-Meter#2]
During complication I got these errors:
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'virtual void esphome::dfrobot_ph_meter::DFRobotPHMeter::setup()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:35:5: error: 'analogReadResolution' was not declared in this scope
   35 |     analogReadResolution(12);
      |     ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:36:26: error: 'ADC_11db' was not declared in this scope
   36 |     analogSetAttenuation(ADC_11db);
      |                          ^~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:36:5: error: 'analogSetAttenuation' was not declared in this scope
   36 |     analogSetAttenuation(ADC_11db);
      |     ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'void esphome::dfrobot_ph_meter::DFRobotPHMeter::reset_calibration()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:56:25: error: 'millis' was not declared in this scope
   56 |   status_reset_timer_ = millis();
      |                         ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'void esphome::dfrobot_ph_meter::DFRobotPHMeter::check_reset_status_()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:183:24: error: 'millis' was not declared in this scope
  183 |   const uint32_t now = millis();
      |                        ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'virtual void esphome::dfrobot_ph_meter::DFRobotPHMeter::loop()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:191:24: error: 'millis' was not declared in this scope
  191 |   const uint32_t now = millis();
      |                        ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:204:15: error: 'analogRead' was not declared in this scope
  204 |     int raw = analogRead(adc_gpio_);
      |               ^~~~~~~~~~
*** [.pioenvs/ph-meter/src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp.o] Error 1

Also I needed to remove the id: ph1 after the dfrobot_ph_meter.calibrate_

compiled using esphome version: 2025.6.0

**Comment by r0bb10** [comment]
it is still probably complaining about missing some includes, try now should be fixed.

about the id: it's because of a typo in the readme, it should reflect the id you specify in the yaml like this

```
dfrobot_ph_meter:
  id: ph_sensor  <--- should match this
  use_ads1115: true
  id_ads1115: ph_voltage_sensor
  channel: 0
  temperature_sensor: water_temp
  temperature_unit: celsius
  update_interval: 10s
  raw_voltage_sensor:
    name: "pH Raw Voltage"
  calibration_mode:
    name: "pH Calibration Mode"
    entity_category: config
  ph_sensor:
    name: "pH Sensor"
    accuracy_decimals: 2
  probe_status_sensor:
    name: "Probe Status"

button:
  - platform: template
    name: "Calibrate pH 4"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.calibrate_ph4:
            id: ph_sensor  <--- should match this
  - platform: template
    name: "Calibrate pH 7"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.calibrate_ph7:
            id: ph_sensor  <--- should match this
  - platform: template
    name: "Calibrate pH 10"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.calibrate_ph10:
            id: ph_sensor  <--- should match this
  - platform: template
    name: "Reset pH Calibration"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.reset_calibration:
            id: ph_sensor  <--- should match this

**Comment by mvroosmalen1970** [comment]
Still not compiling :-(

src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'virtual void esphome::dfrobot_ph_meter::DFRobotPHMeter::setup()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:35:5: error: 'analogReadResolution' was not declared in this scope
   35 |     analogReadResolution(12);
      |     ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:36:26: error: 'ADC_11db' was not declared in this scope
   36 |     analogSetAttenuation(ADC_11db);
      |                          ^~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:36:5: error: 'analogSetAttenuation' was not declared in this scope
   36 |     analogSetAttenuation(ADC_11db);
      |     ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'void esphome::dfrobot_ph_meter::DFRobotPHMeter::reset_calibration()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:56:25: error: 'millis' was not declared in this scope
   56 |   status_reset_timer_ = millis();
      |                         ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'void esphome::dfrobot_ph_meter::DFRobotPHMeter::check_reset_status_()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:183:24: error: 'millis' was not declared in this scope
  183 |   const uint32_t now = millis();
      |                        ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'virtual void esphome::dfrobot_ph_meter::DFRobotPHMeter::loop()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:191:24: error: 'millis' was not declared in this scope
  191 |   const uint32_t now = millis();
      |                        ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:204:15: error: 'analogRead' was not declared in this scope
  204 |     int raw = analogRead(adc_gpio_);
      |               ^~~~~~~~~~
*** [.pioenvs/esp32c3mini3/src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp.o] Error 1
========================= [FAILED] Took 48.56 seconds =========================

**Comment by r0bb10** [comment]
that's wierd, could you post your yaml so i can try to riproduce It? you are using the adc on the esp32 without the ads right?

**Comment by mvroosmalen1970** [comment]
see below the yaml code:
external_components:
  - source:
      type: git
      url: https://github.com/r0bb10/esphome-dfrobot-ph-meter.git
      ref: main
    components: [dfrobot_ph_meter]

bluetooth_proxy:
one_wire:
  - platform: gpio
    pin: GPIO1
sensor:
  - platform: dallas_temp
    name: "Water Temperature"
    id: water_temp
    update_interval: 5s
dfrobot_ph_meter:
  id: ph_sensor
  use_ads1115: false
  adc_pin: 0
#  id_ads1115: ph_voltage_sensor
#  channel: 0
  temperature_sensor: water_temp
  temperature_unit: celsius
  update_interval: 10s
  raw_voltage_sensor:
    name: "pH Raw Voltage"
  calibration_mode:
    name: "pH Calibration Mode"
    entity_category: config
  ph_sensor:
    name: "pH Sensor"
    accuracy_decimals: 2
  probe_status_sensor:
    name: "Probe Status"

button:
  - platform: template
    name: "Calibrate pH 4"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.calibrate_ph4:
            id: ph_sensor
  - platform: template
    name: "Calibrate pH 7"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.calibrate_ph7:
            id: ph_sensor
  - platform: template
    name: "Calibrate pH 10"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.calibrate_ph10:
            id: ph_sensor
  - platform: template
    name: "Reset pH Calibration"
    entity_category: config
    on_press:
      then:
        - dfrobot_ph_meter.reset_calibration:
            id: ph_sensor

**Comment by r0bb10** [comment]
are you using framework esp-idf for the compilation? i can only reproduce the error switching to it from framework arduino while enabling bluetooth_proxy, if yes i need to update the code to support it, try to compile using arduino without bluetooth_proxy it should work then

i will probably support esp-idf soon anyway

```
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

**Comment by mvroosmalen1970** [comment]
Hi

Yes I’m using ESP-idf. So indeed that’s the root cause!

We’ll compile with Arduino for now

Thanks

Mark

I can confirm its complied without errors now!

**Comment by r0bb10** [comment]
yes from arduino to esp-idf there are many differences about how certain stuff is handled, to support both the best way is to auto detect what each user is using and act accordingly.

try the latest patch, it should support esp-idf also now so no need to switch and you can keep bluetooth-proxy also, i tried quickly to compile both and seems to work fine :)

**Comment by mvroosmalen1970** [comment]
mmm 
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'virtual void esphome::dfrobot_ph_meter::DFRobotPHMeter::setup()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:35:5: error: 'analogReadResolution' was not declared in this scope
   35 |     analogReadResolution(12);
      |     ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:36:26: error: 'ADC_11db' was not declared in this scope
   36 |     analogSetAttenuation(ADC_11db);
      |                          ^~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:36:5: error: 'analogSetAttenuation' was not declared in this scope
   36 |     analogSetAttenuation(ADC_11db);
      |     ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'void esphome::dfrobot_ph_meter::DFRobotPHMeter::reset_calibration()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:56:25: error: 'millis' was not declared in this scope
   56 |   status_reset_timer_ = millis();
      |                         ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'void esphome::dfrobot_ph_meter::DFRobotPHMeter::check_reset_status_()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:183:24: error: 'millis' was not declared in this scope
  183 |   const uint32_t now = millis();
      |                        ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp: In member function 'virtual void esphome::dfrobot_ph_meter::DFRobotPHMeter::loop()':
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:191:24: error: 'millis' was not declared in this scope
  191 |   const uint32_t now = millis();
      |                        ^~~~~~
src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp:204:15: error: 'analogRead' was not declared in this scope
  204 |     int raw = analogRead(adc_gpio_);
      |               ^~~~~~~~~~
Compiling .pioenvs/esp32c3mini3/src/esphome/components/esp32/preferences.cpp.o
*** [.pioenvs/esp32c3mini3/src/esphome/components/dfrobot_ph_meter/dfrobot_ph_meter.cpp.o] Error 1
========================= [FAILED] Took 44.53 seconds =========================
when I change back to:
esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf #redundant to core .yml, but left in for clarity
    sdkconfig_options: 
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Also enable this on any derivative boards (S2, C3 etc) but not the original ESP32.
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout, so the device reboots if the device appears locked up for over 10 seconds.
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

**Comment by r0bb10** [comment]
mm i tried to compile exacly your board and works here, wierd

```
esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

bluetooth_proxy:
```

<img width="994" height="545" alt="Image" src="https://github.com/user-attachments/assets/47d9655f-be07-40a6-9e63-c4226f775a92" />

**Comment by mvroosmalen1970** [comment]
Not sure whats the problem, but get this:

<img width="1316" height="670" alt="Image" src="https://github.com/user-attachments/assets/f7bd4633-2c84-446d-93ee-0b5cc3e2b06f" />

with:
esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

bluetooth_proxy:

**Comment by r0bb10** [comment]
it's not detecting the esp-idf but it still tries to compile using arduino i think, try to clear the cache and rebuild the latest version should already address it :S your yaml is correct

**Comment by mvroosmalen1970** [comment]
Haha, indeed added the line refresh:
external_components:
  - source:
      type: git
      url: https://github.com/r0bb10/esphome-dfrobot-ph-meter.git
      ref: main
    components: [dfrobot_ph_meter]
    refresh: 0d
Now its working ;-) Thanks

**Comment by r0bb10** [comment]
eheh good :)
